#############################################################################
# Makefile for building: libdBase.so
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  dbase.pro
# Template: lib
# Command: /home/jens/Qt5.10/5.10.0/gcc_64/bin/qmake -o Makefile dbase.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D'RELATIVE_PLUGIN_PATH="../lib/qtcreator/plugins"' -D'RELATIVE_LIBEXEC_PATH="../libexec/qtcreator"' -D'RELATIVE_DATA_PATH="../share/qtcreator"' -D'RELATIVE_DOC_PATH="../share/doc/qtcreator"' -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fvisibility=hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-noexcept-type -O2 -std=gnu++1y -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../../src -I../../../src -I../../libs -I/home/jens/qtcreator-4.4.1/qt-creator/tools -I../../plugins -I. -I/home/jens/Qt5.10/5.10.0/gcc_64/include -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtConcurrent -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore -I.moc/release-shared -isystem /usr/include/libdrm -I/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++
QMAKE         = /home/jens/Qt5.10/5.10.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/jens/Qt5.10/5.10.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/jens/Qt5.10/5.10.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dBase4.5.82
DISTDIR = /home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase/.obj/release-shared/dBase4.5.82
LINK          = g++
LFLAGS        = -Wl,-z,origin '-Wl,-rpath,$$ORIGIN:$$ORIGIN/..:$$ORIGIN/../lib/qtcreator' -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/home/jens/Qt5.10/5.10.0/gcc_64/lib -shared -Wl,-soname,libdBase.so
LIBS          = $(SUBLIBS) -L/home/jens/qtcreator-4.4.1/qt-creator/lib/qtcreator -L/home/jens/qtcreator-4.4.1/qt-creator/lib/qtcreator/plugins -lCore -lAggregation -lExtensionSystem -lUtils -L/home/jens/Qt5.10/5.10.0/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Concurrent -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/release-shared/

####### Files

SOURCES       = dbaseplugin.cpp \
		dbasewindow.cpp .moc/release-shared/moc_dbaseplugin.cpp \
		.moc/release-shared/moc_dbasewindow.cpp
OBJECTS       = .obj/release-shared/dbaseplugin.o \
		.obj/release-shared/dbasewindow.o \
		.obj/release-shared/moc_dbaseplugin.o \
		.obj/release-shared/moc_dbasewindow.o
DIST          = dbase.qbs \
		dBase.json \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/linux.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/sanitize.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/qconfig.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/toolchain.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_pre.prf \
		dbase_dependencies.pri \
		../coreplugin/coreplugin_dependencies.pri \
		../../libs/extensionsystem/extensionsystem_dependencies.pri \
		../../libs/aggregation/aggregation_dependencies.pri \
		../../libs/utils/utils_dependencies.pri \
		../../../qtcreator.pri \
		../../rpath.pri \
		../../qtcreatorplugin.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_post.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/hide_symbols.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resources.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/moc.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/uic.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/file_copies.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exceptions.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/yacc.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/lex.prf \
		dbase.pro dbaseplugin.h \
		dbasewindow.h dbaseplugin.cpp \
		dbasewindow.cpp
QMAKE_TARGET  = dBase
DESTDIR       = ../../../lib/qtcreator/plugins/
TARGET        = libdBase.so
TARGETD       = libdBase.so


first: all
####### Build rules

../../../lib/qtcreator/plugins/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../../lib/qtcreator/plugins/ || mkdir -p ../../../lib/qtcreator/plugins/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../../lib/qtcreator/plugins/ 



Makefile: dbase.pro /home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf /home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/linux.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/sanitize.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/qconfig.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/toolchain.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_pre.prf \
		dbase_dependencies.pri \
		../coreplugin/coreplugin_dependencies.pri \
		../../libs/extensionsystem/extensionsystem_dependencies.pri \
		../../libs/aggregation/aggregation_dependencies.pri \
		../../libs/utils/utils_dependencies.pri \
		../../../qtcreator.pri \
		../../rpath.pri \
		../../qtcreatorplugin.pri \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_post.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/hide_symbols.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resources.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/moc.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/uic.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/file_copies.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exceptions.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/yacc.prf \
		/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/lex.prf \
		dbase.pro \
		/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Widgets.prl \
		/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Gui.prl \
		/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Concurrent.prl \
		/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile dbase.pro
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_pre.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/unix.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/linux.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/sanitize.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-base.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/common/g++-unix.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/qconfig.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_functions.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt_config.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/toolchain.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_pre.prf:
dbase_dependencies.pri:
../coreplugin/coreplugin_dependencies.pri:
../../libs/extensionsystem/extensionsystem_dependencies.pri:
../../libs/aggregation/aggregation_dependencies.pri:
../../libs/utils/utils_dependencies.pri:
../../../qtcreator.pri:
../../rpath.pri:
../../qtcreatorplugin.pri:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resolve_config.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/default_post.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/hide_symbols.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/warn_on.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qt.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/resources.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/moc.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/uic.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/unix/thread.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/qmake_use.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/file_copies.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/exceptions.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/yacc.prf:
/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/lex.prf:
dbase.pro:
/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Widgets.prl:
/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Gui.prl:
/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Concurrent.prl:
/home/jens/Qt5.10/5.10.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile dbase.pro

qmake_all: FORCE


all: Makefile ../../../lib/qtcreator/plugins/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dbaseplugin.h dbasewindow.h $(DISTDIR)/
	$(COPY_FILE) --parents dbaseplugin.cpp dbasewindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../../lib/qtcreator/plugins/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: .moc/release-shared/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .moc/release-shared/moc_predefs.h
.moc/release-shared/moc_predefs.h: /home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-noexcept-type -O2 -std=gnu++1y -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -dM -E -o .moc/release-shared/moc_predefs.h /home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: .moc/release-shared/moc_dbaseplugin.cpp .moc/release-shared/moc_dbasewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/release-shared/moc_dbaseplugin.cpp .moc/release-shared/moc_dbasewindow.cpp
.moc/release-shared/moc_dbaseplugin.cpp: ../../libs/extensionsystem/iplugin.h \
		../../libs/extensionsystem/extensionsystem_global.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QLoggingCategory \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qloggingcategory.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlogging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qflags.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmutex.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdebug.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhash.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qchar.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiterator.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstring.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringview.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpair.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qregexp.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlocale.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvariant.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvector.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpoint.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qset.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QObject \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QtPlugin \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qplugin.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qjsonobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qjsonvalue.h \
		dbaseplugin.h \
		.moc/release-shared/moc_predefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/bin/moc
	/home/jens/Qt5.10/5.10.0/gcc_64/bin/moc $(DEFINES) --include /home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase/.moc/release-shared/moc_predefs.h -I/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++ -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase -I/home/jens/qtcreator-4.4.1/qt-creator/src -I/home/jens/qtcreator-4.4.1/qt-creator/src -I/home/jens/qtcreator-4.4.1/qt-creator/src/libs -I/home/jens/qtcreator-4.4.1/qt-creator/tools -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase -I/home/jens/Qt5.10/5.10.0/gcc_64/include -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtConcurrent -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore -I/usr/local/include/c++/6.3.0 -I/usr/local/include/c++/6.3.0/x86_64-pc-linux-gnu -I/usr/local/include/c++/6.3.0/backward -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dbaseplugin.h -o .moc/release-shared/moc_dbaseplugin.cpp

.moc/release-shared/moc_dbasewindow.cpp: /home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QWidget \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlogging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qflags.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmutex.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtgui-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstring.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qchar.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringview.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiterator.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpair.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qregexp.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmargins.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrect.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsize.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpoint.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpalette.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcolor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgb.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgba64.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qbrush.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvector.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qmatrix.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpolygon.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qregion.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdatastream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qline.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtransform.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qimage.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixelformat.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhash.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfont.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcursor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvariant.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdebug.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlocale.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qset.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurlquery.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfile.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qvector2d.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtouchdevice.h \
		dbasewindow.h \
		.moc/release-shared/moc_predefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/bin/moc
	/home/jens/Qt5.10/5.10.0/gcc_64/bin/moc $(DEFINES) --include /home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase/.moc/release-shared/moc_predefs.h -I/home/jens/Qt5.10/5.10.0/gcc_64/mkspecs/linux-g++ -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase -I/home/jens/qtcreator-4.4.1/qt-creator/src -I/home/jens/qtcreator-4.4.1/qt-creator/src -I/home/jens/qtcreator-4.4.1/qt-creator/src/libs -I/home/jens/qtcreator-4.4.1/qt-creator/tools -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins -I/home/jens/qtcreator-4.4.1/qt-creator/src/plugins/dbase -I/home/jens/Qt5.10/5.10.0/gcc_64/include -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtConcurrent -I/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore -I/usr/local/include/c++/6.3.0 -I/usr/local/include/c++/6.3.0/x86_64-pc-linux-gnu -I/usr/local/include/c++/6.3.0/backward -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dbasewindow.h -o .moc/release-shared/moc_dbasewindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

.obj/release-shared/dbaseplugin.o: dbaseplugin.cpp dbaseplugin.h \
		../../libs/extensionsystem/iplugin.h \
		../../libs/extensionsystem/extensionsystem_global.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QLoggingCategory \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qloggingcategory.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlogging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qflags.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmutex.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdebug.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhash.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qchar.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiterator.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstring.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringview.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpair.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qregexp.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlocale.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvariant.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvector.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpoint.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qset.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QObject \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QtPlugin \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qplugin.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qjsonobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qjsonvalue.h \
		../../plugins/coreplugin/actionmanager/actionmanager.h \
		../../plugins/coreplugin/core_global.h \
		../../plugins/coreplugin/coreconstants.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QtGlobal \
		../../plugins/coreplugin/icontext.h \
		../../plugins/coreplugin/id.h \
		../coreplugin/core_global.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QMetaType \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QString \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/QList \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtgui-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qregion.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrect.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmargins.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsize.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdatastream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurlquery.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfile.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qvector2d.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtouchdevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QPointer \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QWidget \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpalette.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcolor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgb.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgba64.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qbrush.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qmatrix.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpolygon.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qline.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtransform.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qimage.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixelformat.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfont.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcursor.h \
		../../plugins/coreplugin/actionmanager/command.h \
		../../libs/utils/hostosinfo.h \
		../../libs/utils/utils_global.h \
		../../libs/utils/osspecificaspects.h \
		../../plugins/coreplugin/actionmanager/actioncontainer.h \
		../../plugins/coreplugin/icore.h \
		../coreplugin/id.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QRect \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QSettings \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsettings.h \
		../../plugins/coreplugin/imode.h \
		../coreplugin/icontext.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/QIcon \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qicon.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QMenu \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qmenu.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qaction.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qactiongroup.h \
		../../plugins/coreplugin/modemanager.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/QDebug \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QAction \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QMessageBox \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qdialog.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QPushButton \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qabstractbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/dbaseplugin.o dbaseplugin.cpp

.obj/release-shared/dbasewindow.o: dbasewindow.cpp dbasewindow.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QWidget \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobal.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qconfig.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlogging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qflags.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmutex.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtgui-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstring.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qchar.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringview.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiterator.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpair.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qregexp.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmargins.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qrect.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsize.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qpoint.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpalette.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcolor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgb.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qrgba64.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qbrush.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvector.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qmatrix.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpolygon.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qregion.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdatastream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qline.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtransform.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qimage.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixelformat.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpixmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qhash.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfont.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qcursor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qevent.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qvariant.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qmap.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qdebug.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qlocale.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qset.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurl.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qurlquery.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfile.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qvector2d.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtouchdevice.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QTextEdit \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qtextedit.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qframe.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtextdocument.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtextoption.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtextcursor.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qtextformat.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtGui/qpen.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qlayout.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/jens/Qt5.10/5.10.0/gcc_64/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/dbasewindow.o dbasewindow.cpp

.obj/release-shared/moc_dbaseplugin.o: .moc/release-shared/moc_dbaseplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_dbaseplugin.o .moc/release-shared/moc_dbaseplugin.cpp

.obj/release-shared/moc_dbasewindow.o: .moc/release-shared/moc_dbasewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_dbasewindow.o .moc/release-shared/moc_dbasewindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/lib/qtcreator/plugins || mkdir -p $(INSTALL_ROOT)/lib/qtcreator/plugins
	-$(QINSTALL_PROGRAM) ../../../lib/qtcreator/plugins/$(TARGET) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

